# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(null=True, upload_to='mp3/static/upload')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
