# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
