# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0004_audiofile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='cover',
            field=models.ImageField(default='mp3/static/albumCover/cdp.png', upload_to='mp3/static/albumCover'),
        ),
    ]
