# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0005_auto_20160831_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='cover',
        ),
    ]
